import { RepoSummary } from '@lib/repo-summaries';
import { defineCollection } from 'astro:content';

const githubCollection = defineCollection({
  type: "data",
  schema: RepoSummary,
});

export const collections = {
  // This directory is generated by `pnpm scan`.
  'github': githubCollection,
};
